// The goal of this grammar was an exercise in understanding the structure of the proprietary language Smartassembly (*.tab)

// Given the nature of the business model of this automation language - no formal language specification is available, no CST or AST are provided to users, and there are no existing independent compiler/translators that can be used in pair with the debugger of an IDE to debug the language easily at runtime / support major refactorings / etc.

// idea - we want to preparse a .TAB program  for the names of all of the program variables / data structures

// this enables to automate deep logging of Smartassembly automations, as well as support things like refactoring.

// NOTE: this wont find dynamically-assigned variable names 

// strategies -----

// ignore commments

// ignore whitespace / tabs 

// FIXME: currently ignores table block contents and other special blocks

// DATA STRUCTURES - outputs of specific functions

// variables / params ------ 

// 		DECLARE_VARIABLE*** 

// maps ---------

// 		DECLARE_MAP** 

// structs---------

// 		DECLARE_STRUCT** 

// arrays ----------

// 		DECLARE_ARRAY* 

grammar SADATA;

//  BLOCK RELATED ================================================

// BREAK DOWN A PROGRAM INTO BLOCKS
program: big_block+ EOF;

// Different main blocks to parse / consider - providing for allowable order
big_block:
	asm_block
	| gui_block
	| table_block
	| comp_block
	| dep_block
	| non_relevant_content;

// ROUGH BLOCK DEFINITION - based on start/end tokens and whether the content will be parsed as relevent
gui_block: BEGIN_GUI_DESCR eol relevant_content END_GUI_DESCR;
asm_block: BEGIN_ASM_DESCR eol relevant_content END_ASM_DESCR;
table_block:
	BEGIN_TABLE_DESCR eol non_relevant_content END_TABLE_DESCR;
comp_block:
	BEGIN_COMP_DESCR eol non_relevant_content END_COMP_DESCR;
dep_block:
	BEGIN_DEP_DESCR eol non_relevant_content END_DEP_DESCR;

// CODE CLASSIFICATION ============================================
relevant_content: (line | non_relevant_line)+;
non_relevant_content: (line | non_relevant_line)+;
line: ( functional_expression eol | argument+ eol);
non_relevant_line: eol;
eol: (SINGLE_LINE_COMMENT | NEWLINE | MULTI_LINE_COMMENT);

// BREAKING DOWN LANGUAGE FUNCTION SYNTAX BASED ON RELEVANCE TO CREATING/ASSIGNING DATA STRUCTURES
functional_expression:
	funct_1
	| funct_2
	| funct_3
	| funct_4
	| funct_5
	| funct_6
	| funct_7
	| funct_8;

// This is essentially a bunch of switch cases for where the data structure name will be based on function

// last one args
funct_1: FUNCT_1 argument*? data_structure_of_interest;

// last two args
funct_2:
	FUNCT_2 argument*? data_structure_of_interest data_structure_of_interest;

// last three args
funct_3:
	FUNCT_3 argument*? data_structure_of_interest data_structure_of_interest
		data_structure_of_interest;

// last four args
funct_4:
	FUNCT_4 argument*? data_structure_of_interest data_structure_of_interest
		data_structure_of_interest data_structure_of_interest;

// second arg
funct_5: FUNCT_5 data_structure_of_interest argument*?;

// third arg
funct_6: FUNCT_6 argument data_structure_of_interest argument*?;

// fourth arg
funct_7:
	FUNCT_7 argument argument data_structure_of_interest argument*?;

// 4+ arg
funct_8:
	FUNCT_8 argument argument argument data_structure_of_interest+;

data_structure_of_interest: ID_CANDIDATE | STRUCT_CANDIDATE;

argument:
	RAW_STATEMENT
	| ID_CANDIDATE
	| STRUCT_CANDIDATE
	| STRING;

FUNCT_1:
	'ADD_DRW_TABLE_COL'
	| 'ADD_DRW_TABLE_ROW'
	| 'ASSIGN_VALUE'
	| 'BINARY_FILE_READ'
	| 'BOOLEAN_BODY_OPERATION'
	| 'BUILD_FILE_NAME'
	| 'CALC_CLEARANCE'
	| 'CALC_CURVE_POINT'
	| 'CALC_CURVE_POINTS'
	| 'CALC_FEATURE_DIFF'
	| 'CALC_FEATURE_OUTLINE'
	| 'CALC_FORMULA'
	| 'CALC_FRACTION'
	| 'CALC_GLOBAL_INTERFERENCE'
	| 'CALC_ORIENTATION'
	| 'CALC_OUTLINE'
	| 'CALC_OUTLINE_PARAM'
	| 'CALC_PARAM_POS'
	| 'CALC_RAY_INTERSECTION'
	| 'CALC_SURFACE_SIDE'
	| 'CALC_TRANSFORM_POINT'
	| 'CALC_TRANSFORM_VECTOR'
	| 'CALC_TRANSFORMATION'
	| 'CHECK_COMMON_FEAT_PARAM'
	| 'CHECK_COMMON_MDL_PARAM'
	| 'CHECK_EXTRUDE_OUTLINE'
	| 'CHOOSE_FILE'
	| 'CHOOSE_FILES'
	| 'CHOOSE_PATH'
	| 'COMPARE_MDLS'
	| 'COMPARE_REF_ORDER'
	| 'CONCAT_TRANSFORMATION'
	| 'CONVERT_HOLE_DATA'
	| 'CONVERT_MATRIX_TO_TRANSFORMATION'
	| 'CONVERT_TRANSFORMATION_TO_MATRIX'
	| 'COPY_REF'
	| 'CREATE_ANNOTATION'
	| 'CREATE_ANNOTATION_PLANE'
	| 'CREATE_BODY'
	| 'CREATE_COLLECTION'
	| 'CREATE_COPY_GEOMETRY'
	| 'CREATE_DATUM_TAG'
	| 'CREATE_DATUM_TARGET'
	| 'CREATE_DIM_ANNOTATION'
	| 'CREATE_DRW'
	| 'CREATE_DRW_NOTE_EX'
	| 'CREATE_DRW_TABLE'
	| 'CREATE_DRW_VIEW_DETAIL'
	| 'CREATE_DRW_VIEW_DETAIL_CIRCLE'
	| 'CREATE_DRW_VIEW_DIM_ORDINATE_BASELINE'
	| 'CREATE_DRW_VIEW_GENERAL'
	| 'CREATE_DRW_VIEW_PROJECTION'
	| 'CREATE_FIELD_POINT'
	| 'CREATE_GENERAL_CSYS'
	| 'CREATE_GENERAL_MERGE'
	| 'CREATE_GENERAL_PATTERN'
	| 'CREATE_GENERAL_POINT'
	| 'CREATE_GTOL'
	| 'CREATE_GTOL_CREO4'
	| 'CREATE_HOLE'
	| 'CREATE_IDENTIFIER'
	| 'CREATE_NOTE_EX'
	| 'CREATE_POINTS'
	| 'CREATE_POINTS_EX'
	| 'CREATE_PUBLISHED_GEOMETRY'
	| 'CREATE_SHRINKWRAP'
	| 'CREATE_SMT_FLAT_PATTERN'
	| 'CREATE_SMT_FORM'
	| 'CREATE_SURFFINISH'
	| 'CREATE_UNIQUE_STRING'
	| 'CREATE_XSEC_EX'
	| 'DDM_CHECKOUT_OBJECT'
	| 'DECLARE_ARRAY'
	| 'DECLARE_MAP'
	| 'DECLARE_STOPWATCH'
	| 'DECLARE_STRUCT'
	| 'EXCEL_GET_ACTIVE_SHEET'
	| 'EXCEL_GET_DOCUMENT_NAME'
	| 'EXCEL_GET_DOCUMENT_READONLY'
	| 'EXCEL_GET_FILE_EXTENSION'
	| 'EXCEL_GET_SELECTION'
	| 'EXCEL_GET_SHEET_NAME'
	| 'EXCEL_GET_SHEET_NAMES'
	| 'EXCEL_GET_STRING'
	| 'EXCEL_GET_STRING_BUFFER'
	| 'EXCEL_GET_STRINGS'
	| 'EXCEL_GET_VALUE'
	| 'EXCEL_GET_VALUE_BUFFER'
	| 'EXCEL_GET_VALUES'
	| 'EXEC_MDLCHECK'
	| 'EXPORT_NC_TOOL_XML'
	| 'FILE_OPEN'
	| 'FILE_OPEN_DIALOG'
	| 'FILE_READ'
	| 'FILE_READ_LINE'
	| 'FILE_SAVE_DIALOG'
	| 'FIND_ARRAY_ELEM'
	| 'GENERATE_RANDOM_INT'
	| 'GET_ACTIVE_COMB_VIEW'
	| 'GET_ACTIVE_EXPLODE_STATE'
	| 'GET_ACTIVE_LAYER_STATE'
	| 'GET_ACTIVE_NC_OPERATION'
	| 'GET_ACTIVE_SIMPREP'
	| 'GET_ACTIVE_STYLE'
	| 'GET_ACTIVE_XSEC'
	| 'GET_ANNOTATION_ANGLE'
	| 'GET_ANNOTATION_ELEMENT'
	| 'GET_ANNOTATION_ELEMENT_NAME'
	| 'GET_ANNOTATION_ELEMENT_REFS'
	| 'GET_ANNOTATION_ELEMENTS'
	| 'GET_ANNOTATION_ENVELOPE'
	| 'GET_ANNOTATION_LEADER_REF'
	| 'GET_ANNOTATION_LEADER_REFS'
	| 'GET_ANNOTATION_LEGACY_STATE'
	| 'GET_ANNOTATION_ORIENTATION'
	| 'GET_ANNOTATION_PLANE'
	| 'GET_ANNOTATION_PLANE_NAME'
	| 'GET_ANNOTATION_PLANES'
	| 'GET_ANNOTATION_POS'
	| 'GET_ANNOTATION_REFS'
	| 'GET_ANNOTATION_TEXT_STYLE'
	| 'GET_ARC_DATA'
	| 'GET_ARRAY_ELEM'
	| 'GET_ARRAY_SIZE'
	| 'GET_ATTRIBUTE_DESIGNATION_STATUS'
	| 'GET_AUDIT_TRAIL'
	| 'GET_AXIS_DATA'
	| 'GET_BACKGROUND_VIEW'
	| 'GET_BODY_DENSITY'
	| 'GET_BODY_FROM_REF'
	| 'GET_BODY_MASS_PROPERTIES'
	| 'GET_BODY_MATERIAL'
	| 'GET_BODY_MATERIAL_PROPERTIES'
	| 'GET_BODY_MATERIAL_PROPERTY'
	| 'GET_BREAKABLE_MDL_DEPENDENCY_STATE'
	| 'GET_BROWSER_SIZE'
	| 'GET_CLIPBOARD_TEXT'
	| 'GET_COL_ARRAY'
	| 'GET_COLLECTION_REFS'
	| 'GET_COLOR_PROPS_ASSIGNED'
	| 'GET_COMB_VIEW_ANNOTATION_VISIBILITY'
	| 'GET_COMB_VIEW_ANNOTATIONS'
	| 'GET_COMB_VIEW_PROPS'
	| 'GET_COMB_VIEW_PUBLISH_STATE'
	| 'GET_COMB_VIEW_VISIBILITY_CONTROL'
	| 'GET_COMB_VIEWS'
	| 'GET_COMMON_NAME'
	| 'GET_COMP_BOM_LEVEL'
	| 'GET_COMP_PLACED'
	| 'GET_COMP_TYPE'
	| 'GET_COMPCURVE_CURVES'
	| 'GET_CONFIG_HTML_DATA'
	| 'GET_CONFIG_OPTION'
	| 'GET_CONSEC_FEAT_PARAM_INDEX'
	| 'GET_CONSEC_MDL_PARAM_INDEX'
	| 'GET_CONSTRUCTION_BODY_FLAG_BODY'
	| 'GET_CSYS_ORIENTATION'
	| 'GET_CSYS_VECTOR'
	| 'GET_CURRENT_MDL'
	| 'GET_CURRENT_WORKSPACE'
	| 'GET_CURVE_AT_POS'
	| 'GET_CURVE_COMPCURVE'
	| 'GET_CURVE_LENGTH'
	| 'GET_CURVE_PNT_RATIO'
	| 'GET_CURVE_RATIO_POS'
	| 'GET_CURVE_TESSELLATION'
	| 'GET_CURVE_TYPE'
	| 'GET_CURVES_AT_POS'
	| 'GET_DATUM_TAG_ATTACHMENT'
	| 'GET_DATUM_TAG_LABEL'
	| 'GET_DEFAULT_BODY'
	| 'GET_DENSITY'
	| 'GET_DESIGN_SERVER_INFO'
	| 'GET_DESIGN_SERVER_VARIABLE'
	| 'GET_DIM_ANNOTATION_ORIGIN'
	| 'GET_DIM_BOUND'
	| 'GET_DIM_DECIMALS'
	| 'GET_DIM_DISPLAY_ROUNDED'
	| 'GET_DIM_DISPLAY_ROUNDED_ACCESSIBLE'
	| 'GET_DIM_DISPLAY_TYPE'
	| 'GET_DIM_FEATURE'
	| 'GET_DIM_FRACTIONAL'
	| 'GET_DIM_MDL'
	| 'GET_DIM_OVERRIDE_VALUE'
	| 'GET_DIM_PREFIX'
	| 'GET_DIM_SETUP_TYPE'
	| 'GET_DIM_SUFFIX'
	| 'GET_DIM_SYMBOL'
	| 'GET_DIM_TEXT'
	| 'GET_DIM_TOL_DECIMALS'
	| 'GET_DIM_TOL_TYPE'
	| 'GET_DIM_TYPE'
	| 'GET_DIM_VALUE'
	| 'GET_DIM_VALUE_DISPLAY_TYPE'
	| 'GET_DRF_CSYS'
	| 'GET_DRF_CSYS_DEINFED'
	| 'GET_DRF_CSYS_ORIENTATION'
	| 'GET_DRW_ANNOTATION_POS'
	| 'GET_DRW_ANNOTATION_TEXT_STYLE'
	| 'GET_DRW_ANNOTATION_VISIBILITY'
	| 'GET_DRW_CUR_SHEET'
	| 'GET_DRW_DIM_ATTACHED'
	| 'GET_DRW_DIM_TEXT_ANGLE'
	| 'GET_DRW_FORMAT'
	| 'GET_DRW_FORMAT_TABLES'
	| 'GET_DRW_ITEM_STATE'
	| 'GET_DRW_MDL'
	| 'GET_DRW_MDLS'
	| 'GET_DRW_NOTE_ANGLE'
	| 'GET_DRW_NOTE_OWNER'
	| 'GET_DRW_NOTE_TEXT'
	| 'GET_DRW_NOTE_TEXT_FONT'
	| 'GET_DRW_NOTE_TEXT_HEIGHT'
	| 'GET_DRW_OPTIONS'
	| 'GET_DRW_REF_VIEW'
	| 'GET_DRW_SCALE'
	| 'GET_DRW_SHEET_NUM'
	| 'GET_DRW_SYMBOL_GROUP_EXCLUSIVE'
	| 'GET_DRW_SYMBOL_GROUP_SHOWN'
	| 'GET_DRW_SYMBOL_NAME'
	| 'GET_DRW_SYMBOL_VAR_TEXT'
	| 'GET_DRW_TABLE'
	| 'GET_DRW_TABLE_CELL_REGION'
	| 'GET_DRW_TABLE_COL_WIDTH'
	| 'GET_DRW_TABLE_FORMAT'
	| 'GET_DRW_TABLE_FROM_ID'
	| 'GET_DRW_TABLE_GROWTH_DIR'
	| 'GET_DRW_TABLE_ID'
	| 'GET_DRW_TABLE_NOTE'
	| 'GET_DRW_TABLE_ROW_HEIGHT'
	| 'GET_DRW_TABLE_SHEET'
	| 'GET_DRW_TABLE_TEXT'
	| 'GET_DRW_TOL_STANDARD'
	| 'GET_DRW_VIEW_AXIS'
	| 'GET_DRW_VIEW_DIM_METHOD'
	| 'GET_DRW_VIEW_DIM_REFS'
	| 'GET_DRW_VIEW_DISPLAY'
	| 'GET_DRW_VIEW_MATRIX'
	| 'GET_DRW_VIEW_MDL'
	| 'GET_DRW_VIEW_NAME'
	| 'GET_DRW_VIEW_NORM_SURFACES'
	| 'GET_DRW_VIEW_ORIENTATION'
	| 'GET_DRW_VIEW_OUTLINE'
	| 'GET_DRW_VIEW_PNT_ORIENT'
	| 'GET_DRW_VIEW_REF_POS'
	| 'GET_DRW_VIEW_SECTION_FLIP'
	| 'GET_DRW_VIEW_SECTION_NAME'
	| 'GET_DRW_VIEW_SECTION_NUM'
	| 'GET_DRW_VIEW_SECTION_TYPE'
	| 'GET_DRW_VIEW_SIMPREP'
	| 'GET_DRW_VIEW_STATE'
	| 'GET_DRW_VIEW_TYPE'
	| 'GET_EDGE_AT_POS'
	| 'GET_EDGE_LENGTH'
	| 'GET_EDGE_PNT_RATIO'
	| 'GET_EDGE_TYPE'
	| 'GET_EDGES_AT_POS'
	| 'GET_ENUMERATED_FEAT_PARAM_VALUES'
	| 'GET_ENUMERATED_MDL_PARAM_VALUES'
	| 'GET_ENUMERATED_REF_PARAM_VALUES'
	| 'GET_ENVIRONMENT_VARIABLE'
	| 'GET_EXPLODE_STATE'
	| 'GET_EXTERNAL_DATA_CLASSES'
	| 'GET_EXTERNAL_DATA_SLOTS'
	| 'GET_FAMINSTANCE_LOCK_STATUS'
	| 'GET_FAMINSTANCE_NAMES'
	| 'GET_FAMITEM_NAME'
	| 'GET_FAMITEM_STATE'
	| 'GET_FAMITEM_SYMBOL'
	| 'GET_FAMITEM_TYPE'
	| 'GET_FAMITEM_VALUE'
	| 'GET_FAMITEMS'
	| 'GET_FEAT_PARAM_DESCRIPTION'
	| 'GET_FEAT_PARAM_DESIGNATION_STATUS'
	| 'GET_FEAT_PARAM_LOCK_STATUS'
	| 'GET_FEATURE_DEPENDENCY'
	| 'GET_FEATURE_DEPENDENCY_NAME'
	| 'GET_FEATURE_DIMS'
	| 'GET_FEATURE_FORM_TYPE'
	| 'GET_FEATURE_FROM_GEOM'
	| 'GET_FEATURE_NAME'
	| 'GET_FEATURE_NUMBER'
	| 'GET_FEATURE_SKETCH_DIMS_WITH_REFS'
	| 'GET_FEATURE_STATE'
	| 'GET_FEATURE_STATE_EX'
	| 'GET_FEATURE_SUBTYPE_NAME'
	| 'GET_FEATURE_TYPE'
	| 'GET_FEATURE_TYPE_NAME'
	| 'GET_FEATURE_UPDATE_NOTIFICATION'
	| 'GET_FILE_SIZE'
	| 'GET_FILE_TIMESTAMP'
	| 'GET_FLEXBILE'
	| 'GET_FLEXBILE_PREDEFINED'
	| 'GET_GENERAL_MERGE_FEATURE'
	| 'GET_GENERAL_MERGE_FEATURE_NUM'
	| 'GET_GEOM_FROM_FEATURE'
	| 'GET_GEOMS_FROM_FEATURE'
	| 'GET_GROUP_FEATURE'
	| 'GET_GROUP_FEATURE_NUM'
	| 'GET_GROUP_HEAD'
	| 'GET_GTOL_DRFS'
	| 'GET_GTOL_TEXT'
	| 'GET_GTOL_VALUE'
	| 'GET_IDENTIFIER'
	| 'GET_IDENTIFIER_FROM_REF'
	| 'GET_INSERT_MODE_POSITION'
	| 'GET_INTENT_MEMBERS'
	| 'GET_LAYER_ITEMS'
	| 'GET_LAYER_STATE'
	| 'GET_LAYER_STATE_HIDDEN_REFS'
	| 'GET_LAYER_STATE_LAYER_STATUS'
	| 'GET_LAYER_STATE_LAYERS'
	| 'GET_LAYER_STATES'
	| 'GET_LAYER_STATUS'
	| 'GET_LAYER_STATUS_EX'
	| 'GET_LINE_DATA'
	| 'GET_MAP_ELEM'
	| 'GET_MAP_SIZE'
	| 'GET_MASS_PROPERTIES'
	| 'GET_MATERIAL'
	| 'GET_MATERIAL_PROPERTIES'
	| 'GET_MATERIAL_PROPERTY'
	| 'GET_MATERIALS'
	| 'GET_MDL_ACTIVE_ANNOTATION_PLANE'
	| 'GET_MDL_ANNOTATION_PLANE'
	| 'GET_MDL_DEPENDENCIES'
	| 'GET_MDL_DIMS'
	| 'GET_MDL_DTL_OPTION'
	| 'GET_MDL_DTL_OPTIONS'
	| 'GET_MDL_EXTENSION'
	| 'GET_MDL_FAILURE_FLAG'
	| 'GET_MDL_MODIFIED'
	| 'GET_MDL_NAME'
	| 'GET_MDL_NOTEBOOK'
	| 'GET_MDL_NOTEBOOKS'
	| 'GET_MDL_PARAM_DESCRIPTION'
	| 'GET_MDL_PARAM_DESIGNATION_STATUS'
	| 'GET_MDL_PARAM_LOCK_STATUS'
	| 'GET_MDL_PATH'
	| 'GET_MDL_REGEN_STATE'
	| 'GET_MDL_SESSION_ID'
	| 'GET_MDL_SUBTYPE'
	| 'GET_MDL_TEXTS'
	| 'GET_MDL_TOL_CLASS'
	| 'GET_MDL_TOL_STANDARD'
	| 'GET_MDL_TYPE'
	| 'GET_MDL_TYPE_EX'
	| 'GET_MDL_VERSION'
	| 'GET_MFG_ASM'
	| 'GET_MOUSE_POINT'
	| 'GET_NAMED_ORIENTATIONS'
	| 'GET_NC_OPERATION_CSYS'
	| 'GET_NC_OPERATION_PARAM'
	| 'GET_NC_OPERATION_RETRACT_SURFACE'
	| 'GET_NC_OPERATION_STEPS'
	| 'GET_NC_OPERATION_WORKCELL'
	| 'GET_NC_STEP_LEGACY_STATE'
	| 'GET_NC_STEP_PARAM'
	| 'GET_NC_STEP_TOOL_SETUP'
	| 'GET_NC_WORKCELL_PARAM'
	| 'GET_NEXT_MDL_NAME'
	| 'GET_NOTE_OWNER'
	| 'GET_NOTE_TEXT'
	| 'GET_NOTE_URL'
	| 'GET_NUM_NC_HEADS'
	| 'GET_ORIENTATION_MATRIX'
	| 'GET_PATTERN_MEMBER'
	| 'GET_PATTERN_MEMBER_NUM'
	| 'GET_PATTERN_TYPE'
	| 'GET_PDM_LOCK_STATE'
	| 'GET_PDM_STATE'
	| 'GET_PDM_STATE_BY_NAME'
	| 'GET_PDM_STATE_BY_NAME_EX'
	| 'GET_PDM_STATE_EX'
	| 'GET_PDM_STORAGE'
	| 'GET_PIPELINE'
	| 'GET_PNT_INDEX'
	| 'GET_PREDEFINED_FLEXIBLE_ITEMS'
	| 'GET_PRO_PROGRAM_INPUT'
	| 'GET_PROE_DATECODE'
	| 'GET_PROE_MODE'
	| 'GET_QULT_SURFACES'
	| 'GET_REF_ACP_IDS'
	| 'GET_REF_ACP_OWNER'
	| 'GET_REF_ANNOTATION_PLANE'
	| 'GET_REF_CHILD'
	| 'GET_REF_COMMON_PARENT'
	| 'GET_REF_DEPEND_CHILD'
	| 'GET_REF_DEPEND_CHILD_EX'
	| 'GET_REF_DEPEND_CHILDREN'
	| 'GET_REF_DEPEND_CHILDREN_EX'
	| 'GET_REF_DEPEND_PARENT'
	| 'GET_REF_DEPEND_PARENT_EX'
	| 'GET_REF_DEPEND_PARENTS'
	| 'GET_REF_DEPEND_PARENTS_EX'
	| 'GET_REF_FAMINSTANCE'
	| 'GET_REF_GENERIC'
	| 'GET_REF_ID'
	| 'GET_REF_NAME'
	| 'GET_REF_OWNER'
	| 'GET_REF_PARAM_DESCRIPTION'
	| 'GET_REF_PARAM_LOCK_STATUS'
	| 'GET_REF_PARENT'
	| 'GET_REF_POS'
	| 'GET_REF_STATE'
	| 'GET_REF_TYPE'
	| 'GET_REF_UV_PARAM'
	| 'GET_REF_VERTEX'
	| 'GET_REGISTRY_STRING'
	| 'GET_REGISTRY_STRINGS'
	| 'GET_RELATIONS'
	| 'GET_RELATIONS_UNIT_SENSITIVITY'
	| 'GET_ROW_ARRAY'
	| 'GET_SELBUFFER'
	| 'GET_SERVER'
	| 'GET_SERVER_LOCATION'
	| 'GET_SERVERS'
	| 'GET_SESSION_MDLS'
	| 'GET_SMT_BEND_EDGE_CHILD'
	| 'GET_SMT_BEND_EDGE_PARENT'
	| 'GET_SMT_BEND_SURFACE_CHILD'
	| 'GET_SMT_BEND_SURFACE_PARENT'
	| 'GET_SMT_BEND_SURFACE_PROPS'
	| 'GET_SMT_EDGE_OPPOSITE'
	| 'GET_SMT_SURFACE_OPPOSITE'
	| 'GET_SMT_SURFACE_TYPE'
	| 'GET_STOPWATCH_TIME'
	| 'GET_STYLE'
	| 'GET_SURFACE_AT_POS'
	| 'GET_SURFACE_CONTOUR'
	| 'GET_SURFACE_CONTOURS'
	| 'GET_SURFACE_QUILT'
	| 'GET_SURFACE_REV_AXIS'
	| 'GET_SURFACE_SETUP_TYPE'
	| 'GET_SURFACE_TYPE'
	| 'GET_SURFACES_AT_POS'
	| 'GET_SURFFINISH_VALUE'
	| 'GET_SYMBOL_GROUP_EXCLUSIVE'
	| 'GET_SYMBOL_GROUP_SHOWN'
	| 'GET_SYMBOL_NAME'
	| 'GET_SYMBOL_POS'
	| 'GET_SYMBOL_STRING'
	| 'GET_SYMBOL_VAR_TEXT'
	| 'GET_TAB_LIN_NUM'
	| 'GET_TAB_NAME'
	| 'GET_TAB_STACK'
	| 'GET_TAB_STACK_DEPTH'
	| 'GET_TBLPATTERN_DATA'
	| 'GET_TBLPATTERN_TABLES'
	| 'GET_TEXTURE_PROPS'
	| 'GET_TIME_STRING'
	| 'GET_TOPLEVEL_ASMS'
	| 'GET_TOPLEVEL_MDLS'
	| 'GET_UDF_DATA'
	| 'GET_UNIT_FORCE'
	| 'GET_UNIT_LENGTH'
	| 'GET_UNIT_MASS'
	| 'GET_UNIT_SYSTEM'
	| 'GET_UNIT_TEMPERATURE'
	| 'GET_UNIT_TIME'
	| 'GET_URL_FROM_ALIASED_URL'
	| 'GET_VARIABLE_TYPE'
	| 'GET_VARIED_ITEMS'
	| 'GET_VARIED_MDL'
	| 'GET_WITNESS_LINE_DIM'
	| 'GET_WORKING_DIRECTORY'
	| 'GET_WORKSPACE_CONTEXT'
	| 'GET_WORKSPACES'
	| 'GET_XSEC'
	| 'GET_XSEC_PROPERTIES'
	| 'GET_XSEC_TYPE'
	| 'GET_XSECS'
	| 'GOOGLESHEETS_GET_SHEET_NAME'
	| 'GOOGLESHEETS_GET_SHEET_NAMES'
	| 'GOOGLESHEETS_GET_STRING'
	| 'GOOGLESHEETS_GET_STRING_BUFFER'
	| 'GOOGLESHEETS_GET_STRINGS'
	| 'GOOGLESHEETS_GET_VALUE'
	| 'GOOGLESHEETS_GET_VALUE_BUFFER'
	| 'GOOGLESHEETS_GET_VALUES'
	| 'IMPORT_NC_TOOL_XML'
	| 'INFO_ENGINE_QUERY'
	| 'INSERT_DRW_TABLE_COL'
	| 'INSERT_DRW_TABLE_ROW'
	| 'JLINK_APP_LOAD'
	| 'JSON_DOCUMENT_TO_STRING'
	| 'JSON_GET_ARRAY_ELEMS'
	| 'JSON_GET_ARRAY_SIZE'
	| 'JSON_COMPOSE_PATH'
	| 'JSON_GET_NEXT_ARRAY_ELEM'
	| 'JSON_GET_OBJECT_MEMBERS'
	| 'JSON_GET_TYPE'
	| 'JSON_GET_VALUE'
	| 'JSON_INIT_DOCUMENT'
	| 'JSON_LOAD_DOCUMENT'
	| 'JSON_NEW_DOCUMENT'
	| 'LOAD_MDL'
	| 'LOOKUP_FAMINSTANCE'
	| 'LOOKUP_FAMINSTANCES'
	| 'MEASURE_ANGLE'
	| 'MEASURE_AREA'
	| 'MEASURE_DIAMETER'
	| 'MEASURE_DISTANCE'
	| 'MEASURE_LENGTH'
	| 'MESSAGE_BOX_EX'
	| 'MODIFY_NC_STEP'
	| 'ODBC_GET_COLUMN_TYPE'
	| 'ODBC_GET_TABLE_COLUMNS'
	| 'ODBC_GET_TABLES'
	| 'ODBC_QUERY'
	| 'PARSE_STRING_EX'
	| 'PROBE_DRW_SYMBOL_LEGACY'
	| 'READ_ANNOTATION_PLANE'
	| 'READ_COLLECTION'
	| 'READ_COLOR_PROPS'
	| 'READ_DATUM_TAG'
	| 'READ_DATUM_TARGET'
	| 'READ_DIRECTORY'
	| 'READ_DRW_NOTE_EX'
	| 'READ_EXPLODE_STATE'
	| 'READ_EXTERNAL_DATA'
	| 'READ_EXTERNAL_DATA_SLOT'
	| 'READ_FIELD_POINT'
	| 'READ_GENERAL_CSYS'
	| 'READ_GENERAL_PATTERN'
	| 'READ_GENERAL_POINT'
	| 'READ_GTOL'
	| 'READ_GTOL_CREO4'
	| 'READ_HOLE'
	| 'READ_NC_STEP'
	| 'READ_NOTE_EX'
	| 'READ_POINTS_EX'
	| 'READ_SUBDIRECTORIES'
	| 'READ_SURFFINISH'
	| 'READ_SYMBOL'
	| 'READ_TEXTURE_PROPS'
	| 'READ_XSEC_EX'
	| 'REG_EXP_FIND_ALL'
	| 'REG_EXP_REPLACE'
	| 'RESOLVE_PATH'
	| 'RETRIEVE_MDL'
	| 'RETRIEVE_REFERENCE'
	| 'SEARCH_BODY_REF'
	| 'SEARCH_BODY_REFS'
	| 'SEARCH_CUSTOM_SIMPREP'
	| 'SEARCH_CUSTOM_SIMPREPS'
	| 'SEARCH_CUSTOM_STYLE'
	| 'SEARCH_CUSTOM_STYLES'
	| 'SEARCH_DESIGN_SERVER_VARIABLE_NAMES'
	| 'SEARCH_DRW_ITEM'
	| 'SEARCH_DRW_ITEMS'
	| 'SEARCH_DRW_SYMBOL_GROUP_NAMES'
	| 'SEARCH_DRW_SYMBOL_VAR_TEXT'
	| 'SEARCH_DRW_SYMBOL_VAR_TEXT_NAMES'
	| 'SEARCH_DRW_SYMBOLS'
	| 'SEARCH_DRW_TABLES_FOR_MDL'
	| 'SEARCH_DRW_VIEW'
	| 'SEARCH_DRW_VIEW_DIM'
	| 'SEARCH_DRW_VIEW_DIMS'
	| 'SEARCH_DRW_VIEWS'
	| 'SEARCH_ENUMERATED_FEAT_PARAM_NAME'
	| 'SEARCH_ENUMERATED_FEAT_PARAM_NAMES'
	| 'SEARCH_ENUMERATED_MDL_PARAM_NAME'
	| 'SEARCH_ENUMERATED_MDL_PARAM_NAMES'
	| 'SEARCH_ENUMERATED_REF_PARAM_NAME'
	| 'SEARCH_ENUMERATED_REF_PARAM_NAMES'
	| 'SEARCH_FEAT_PARAM'
	| 'SEARCH_FEAT_PARAM_NAME'
	| 'SEARCH_FEAT_PARAM_NAMES'
	| 'SEARCH_FEAT_REF'
	| 'SEARCH_FEAT_REFS'
	| 'SEARCH_FILE_PARAM'
	| 'SEARCH_LINESTOCK_PARAM'
	| 'SEARCH_LINESTOCK_PARAM_EX'
	| 'SEARCH_MDL_OR_COMP_PARAM'
	| 'SEARCH_MDL_PARAM'
	| 'SEARCH_MDL_PARAM_NAME'
	| 'SEARCH_MDL_PARAM_NAMES'
	| 'SEARCH_MDL_REF'
	| 'SEARCH_MDL_REFS'
	| 'SEARCH_REF_PARAM'
	| 'SEARCH_REF_PARAM_NAME'
	| 'SEARCH_REF_PARAM_NAMES'
	| 'SEARCH_RELATION_ELEMENTS'
	| 'SEARCH_RELATIONS'
	| 'SEARCH_STAGE_ORIENT_PLANE'
	| 'SEARCH_STAMP_REF'
	| 'SEARCH_SYMBOL_GROUP_NAMES'
	| 'SEARCH_SYMBOL_VAR_TEXT'
	| 'SEARCH_SYMBOL_VAR_TEXT_NAMES'
	| 'SEARCH_UDF_DIM'
	| 'SEARCH_VARIABLE'
	| 'SEARCH_VARIABLE_NAMES'
	| 'SEARCH_VARIABLES'
	| 'SELECT_FAMINSTANCE'
	| 'SET_DRF_CSYS_ORIENTATION'
	| 'SET_FAMINSTANCE_LOCK_STATUS'
	| 'SETUP_CURVE_COLLECTION'
	| 'SETUP_SURFACE_COLLECTION'
	| 'SHOW_DRW_VIEW_AXIS'
	| 'STRING_TO_REFERENCE'
	| 'SUGGEST_SMT_FIXED_SURFACE'
	| 'TK_APP_LOAD'
	| 'TK_GET_HANDLE_FROM_REGISTRY'
	| 'TOOLKIT_APP_LOAD'
	| 'TRANSPOSE_ARRAY'
	| 'USE_LIBRARY_MDL'
	| 'USER_YESNO_PARAM'
	| 'VECTOR_CROSS_PRODUCT'
	| 'VECTOR_DOT_PRODUCT'
	| 'VECTOR_FROM_POINTS'
	| 'VECTOR_GET_LENGTH'
	| 'VERIFY_RELATIONS'
	| 'WEBSERVICE_CALL'
	| 'WINWORD_GET_ACTIVEX_TEXT'
	| 'WINWORD_GET_BOOKMARK_TEXT'
	| 'WINWORD_GET_BOOKMARKS'
	| 'XML_ADD_NODE'
	| 'XML_COMPARE_NODES'
	| 'XML_DOCUMENT_TO_STRING'
	| 'XML_FORMAT_DOCUMENT'
	| 'XML_GET_ATTRIBUTE_NAME'
	| 'XML_GET_ATTRIBUTE_VALUE'
	| 'XML_GET_NODE'
	| 'XML_GET_NODE_ATTRIBUTE'
	| 'XML_GET_NODE_ATTRIBUTES'
	| 'XML_GET_NODE_NAME'
	| 'XML_GET_NODE_TYPE'
	| 'XML_GET_NODE_VALUE'
	| 'XML_GET_NODES'
	| 'XML_GET_SIBLING_NODE'
	| 'XML_GET_SIBLING_NODES'
	| 'XML_INIT_DOCUMENT'
	| 'XML_LOAD_DOCUMENT'
	| 'XML_NEW_DOCUMENT'
	| 'XML_QUERY_VALUES';

FUNCT_2:
	'CALC_CURVE_EXTREMES'
	| 'CALC_POINT_ON_LINE'
	| 'CALC_POS_PARAM'
	| 'EXCEL_GET_CELL_BY_NAME'
	| 'GET_ACCURACY'
	| 'GET_AUTHENTICATION'
	| 'GET_DIM_TOL'
	| 'GET_DRW_DIM_POS'
	| 'GET_DRW_DIM_TEXT_POS'
	| 'GET_DRW_NOTE_POS'
	| 'GET_DRW_NOTE_TEXT_ALIGNMENT'
	| 'GET_DRW_SYMBOL_POS'
	| 'GET_DRW_TABLE_POS'
	| 'GET_DRW_TABLE_SIZE'
	| 'GET_DRW_VIEW_PNT_COORD'
	| 'GET_DRW_VIEW_POS'
	| 'GET_EDGE_SURFACES'
	| 'GET_PDM_MODIFICATION_STATE'
	| 'GET_PROE_VERSION'
	| 'GET_SMT_UNBEND_FIXED_REF'
	| 'GET_SURFACE_NORM'
	| 'GET_ZOOM_POS'
	| 'PASSWORD_DIALOG'
	| 'READ_COMP_INTERFACE'
	| 'REFERENCE_TO_STRING'
	| 'REG_EXP_MATCH'
	| 'REG_EXP_SEARCH';

FUNCT_3:
	'GET_COLOR'
	| 'GET_DIM_TOL_TABLE'
	| 'GET_DRW_SIZE'
	| 'GET_PNT_COORD'
	| 'GET_SA_VERSION'
	| 'PARSE_FILE_NAME'
	| 'READ_SMT_FORM';

FUNCT_4:
	'EXCEL_GET_ACTIVE_RANGE'
	| 'GET_DRW_TABLE_OUTLINE'
	| 'GOOGLESHEETS_GET_ACTIVE_RANGE';

FUNCT_5: 'DECLARE_REFERENCE' | 'FOR';

FUNCT_6:
	'DECLARE_VARIABLE'
	| 'SPLIT_STRING'
	| 'USER_INPUT_PARAM'
	| 'USER_SELECT'
	| 'USER_SELECT_OPTIONAL';

FUNCT_7:
	'USER_COLLECT'
	| 'USER_SELECT_MULTIPLE'
	| 'USER_SELECT_MULTIPLE_OPTIONAL';

FUNCT_8: 'PARSE_STRING';

// Tokens of blocks definition -----------------
END_GUI_DESCR: 'END_GUI_DESCR';
BEGIN_GUI_DESCR: 'BEGIN_GUI_DESCR';
END_ASM_DESCR: 'END_ASM_DESCR';
BEGIN_ASM_DESCR: 'BEGIN_ASM_DESCR';

END_TABLE_DESCR: 'END_TABLE_DESCR';
BEGIN_TABLE_DESCR: 'BEGIN_TABLE_DESCR';

BEGIN_COMP_DESCR: 'BEGIN_COMP_DESCR';
END_COMP_DESCR: 'END_COMP_DESCR';

BEGIN_DEP_DESCR: 'BEGIN_DEP_DESCR';
END_DEP_DESCR: 'END_DEP_DESCR';

STRING: '"' (ESC | ~["\\])*? '"';

ID_CANDIDATE: (Number | Letter | SemiSpecial)+;

STRUCT_CANDIDATE:
	(Number | Letter | SemiSpecial)+ Period (
		Number
		| Letter
		| SemiSpecial
	)+;

RAW_STATEMENT: (
		Number
		| Letter
		| SemiSpecial
		| Quote
		| Special
		| Period
		| OtherSpecial
	)+;

ESC: '\\' (["\\/bfnrt] | UNICODE);

fragment UNICODE: 'u' HEX HEX HEX HEX;
fragment HEX: [0-9a-fA-F];

fragment Number: [0-9];
fragment Letter: [a-zA-Z];
fragment SemiSpecial: '_' | '-';
fragment Period: '.';

fragment Quote: '"';
fragment Special: [©�$?,+<>%()=:\\@;'*^&/~#];
fragment OtherSpecial: '[' | ']' | '{' | '}' | '|';

SINGLE_LINE_COMMENT: '!' .*? NEWLINE;
MULTI_LINE_COMMENT: '/*' .+? NEWLINE*? '*/' NEWLINE?;
NEWLINE: '\r'? '\n'; // We use newlines syntactically
WHITE:
	[ \t]+ -> channel(HIDDEN); // but we can ignore this whitespace